{% set data= load_setup_py_data() %}
package:
  name: ts-authorize
  version: {{ data.get("version") }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - aiohttp
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
    - aiohttp
  run:
    - python {{ python }}
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - aiohttp
